# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.2.0
group=com.nyfaria.nyfsmultiloader
java_version=21

# Common
minecraft_version=1.21.10
mod_name=Nyf's Banner Patterns
mod_author=Nyfaria
mod_id=nyfsbp
license=ARR
credits=
description=Multiloader Template Modified for the needs of Nyfaria.
minecraft_version_range=[1.21.10, 1.22.11)

# Fabric
fabric_version=0.138.3+1.21.10
fabric_loader_version=0.18.2

# NeoForge
neoforge_version=21.10.64
neoforge_loader_version_range=[2,)
neoForge.parchment.minecraftVersion=1.21.10
neoForge.parchment.mappingsVersion=2025.10.12

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
forge_config_api_port_version=21.10.0
regutils_version=1.21.3-0.1.1

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=846321
modrinth_publishing_enabled=true
modrinth_project_id=6FwNRlG5
dry_run=false